### ISSUE TITLE
Ingestion Task Failing 

### ISSUE THREAD

**Issue by knowvishnu** [druid-io/druid-operator#134]
Description 

i have deployed `tiny-cluster.yml` on eks cluster. all services are in running state. but when i am ingesting example data , its giving Error. The error was comming something like this` java.io.IOException: Unable to create directory /druid/deepstorage/intermediate_pushes/b827a4e4-a807-4009-aeec-29360d404f7c`

is there any need to give permission  to `/druid/deepstorage` to create directory ?

![image](https://user-images.githubusercontent.com/29915623/107230237-cb88e980-6a44-11eb-852e-6949b5e191c3.png)

Logs 
```
INFO: Binding org.apache.druid.server.StatusResource to GuiceManagedComponentProvider with the scope "Undefined"
2021-02-08T12:52:31,415 INFO [main] org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@37806be6{/,null,AVAILABLE}
2021-02-08T12:52:31,463 INFO [main] org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@53e28097{HTTP/1.1, (http/1.1)}{0.0.0.0:8100}
2021-02-08T12:52:31,465 INFO [main] org.eclipse.jetty.server.Server - Started @9304ms
2021-02-08T12:52:31,465 INFO [main] org.apache.druid.java.util.common.lifecycle.Lifecycle - Starting lifecycle [module] stage [ANNOUNCEMENTS]
2021-02-08T12:52:31,465 INFO [main] org.apache.druid.java.util.common.lifecycle.Lifecycle - Successfully started lifecycle [module]
2021-02-08T12:52:32,010 INFO [task-runner-0-priority-0] org.apache.druid.indexing.common.task.IndexTask - Found intervals and shardSpecs in 2,508ms
2021-02-08T12:52:32,010 INFO [task-runner-0-priority-0] org.apache.druid.indexing.common.task.AbstractBatchIndexTask - [forceTimeChunkLock] is set to true in task context. Use timeChunk lock
2021-02-08T12:52:42,283 INFO [task-runner-0-priority-0] org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver - New segment[wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2021-02-08T12:52:41.455Z] for sequenceName[index_parallel_wikipedia_mijagdlh_2021-02-08T12:52:21.883Z].
2021-02-08T12:52:44,310 INFO [task-runner-0-priority-0] org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver - Pushing [1] segments in background
2021-02-08T12:52:44,313 INFO [task-runner-0-priority-0] org.apache.druid.segment.realtime.appenderator.BaseAppenderatorDriver - Pushing segments: [wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2021-02-08T12:52:41.455Z]
2021-02-08T12:52:46,254 INFO [[index_parallel_wikipedia_mijagdlh_2021-02-08T12:52:21.883Z]-appenderator-persist] org.apache.druid.segment.realtime.appenderator.AppenderatorImpl - Flushed in-memory data for segment[wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2021-02-08T12:52:41.455Z] spill[0] to disk in [1,936] ms (24,433 rows).
2021-02-08T12:52:46,338 INFO [[index_parallel_wikipedia_mijagdlh_2021-02-08T12:52:21.883Z]-appenderator-persist] org.apache.druid.segment.realtime.appenderator.AppenderatorImpl - Flushed in-memory data with commit metadata [null] for segments: wikipedia_2016-06-27T00:00:00.000Z_2016-06-28T00:00:00.000Z_2021-02-08T12:52:41.455Z
2021-02-08T12:52:47,283 WARN [[index_parallel_wikipedia_mijagdlh_2021-02-08T12:52:21.883Z]-appenderator-merge] org.apache.druid.java.util.common.RetryUtils - Retrying (1 of 4) in 1,296ms.
java.io.IOException: Unable to create directory /druid/deepstorage/intermediate_pushes/b827a4e4-a807-4009-aeec-29360d404f7c
	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:2491) ~[commons-io-2.6.jar:2.6]
	at org.apache.druid.segment.loading.LocalDataSegmentPusher.push(LocalDataSegmentPusher.java:86) ~[druid-server-0.20.1.jar:0.20.1]
	at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.lambda$mergeAndPush$4(AppenderatorImpl.java:794) ~[druid-server-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:87) ~[druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:115) ~[druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:105) ~[druid-core-0.20.1.jar:0.20.1]
	at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.mergeAndPush(AppenderatorImpl.java:790) ~[druid-server-0.20.1.jar:0.20.1]
	at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.lambda$push$1(AppenderatorImpl.java:660) ~[druid-server-0.20.1.jar:0.20.1]
	at com.google.common.util.concurrent.Futures$1.apply(Futures.java:713) [guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861) [guava-16.0.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Comment by knowvishnu** [comment]
i have changed `deepstorage-volume` volumeType to `emptyDir`. then its working.

**Comment by jphavoc** [comment]
I encountered the same error. Any suggestions?

**Comment by knowvishnu** [comment]
In the case of deep-storage `local` it was not working. 
so i changed the deep storage with the `aws s3`. then it was working fine.

One more thing try to remove these 2 configuration. check this will work or not in case of deepstorage `local`

```
 - mountPath: /druid/deepstorage
      name: deepstorage-volume
```

```
 - name: deepstorage-volume
      hostPath:
        path: /tmp/druid/deepstorage
        type: DirectoryOrCreate
```
