### ISSUE TITLE
Tasks failed to run from Kafka Ingester

### ISSUE THREAD

**Issue by samitks** [druid-io/druid-operator#159]
Hi Team,

We setup a druid cluster on k8s.
When we started running a supervisor which ingest from kafka topics, we are getting the following error in the middle-manager pod.

> 1) Error in custom provider, java.lang.NumberFormatException: For input string: "1druid.host=10.19.218.148"
  at org.apache.druid.guice.ConfigProvider.bind(ConfigProvider.java:44) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.DruidProcessingConfigModule)
  at org.apache.druid.guice.ConfigProvider.bind(ConfigProvider.java:44) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.DruidProcessingConfigModule)
  while locating org.apache.druid.query.DruidProcessingConfig
  while locating org.apache.druid.segment.column.ColumnConfig
    for the 2nd parameter of org.apache.druid.segment.IndexIO.<init>(IndexIO.java:102)
  while locating org.apache.druid.segment.IndexIO
    for the 17th parameter of org.apache.druid.indexing.common.TaskToolboxFactory.<init>(TaskToolboxFactory.java:120)
  at org.apache.druid.cli.CliPeon.bindTaskConfigAndClients(CliPeon.java:400) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliPeon$1)
  while locating org.apache.druid.indexing.common.TaskToolboxFactory
    for the 1st parameter of org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner.<init>(SingleTaskBackgroundRunner.java:95)
  at org.apache.druid.cli.CliPeon$1.configure(CliPeon.java:210) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliPeon$1)
  while locating org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner
  while locating org.apache.druid.indexing.overlord.TaskRunner
    for the 4th parameter of org.apache.druid.indexing.worker.executor.ExecutorLifecycle.<init>(ExecutorLifecycle.java:80)
  at org.apache.druid.cli.CliPeon$1.configure(CliPeon.java:194) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliPeon$1)
  while locating org.apache.druid.indexing.worker.executor.ExecutorLifecycle
Caused by: java.lang.NumberFormatException: For input string: "1druid.host=10.19.218.148"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.skife.config.DefaultCoercibles$16.coerce(DefaultCoercibles.java:255)
	at org.skife.config.DefaultCoercibles$16.coerce(DefaultCoercibles.java:253)
	at org.skife.config.Bully.coerce(Bully.java:164)
	at org.skife.config.Bully.coerce(Bully.java:81)
	at org.skife.config.ConfigurationObjectFactory.buildSimple(ConfigurationObjectFactory.java:173)
	at org.skife.config.ConfigurationObjectFactory.internalBuild(ConfigurationObjectFactory.java:76)
	at org.skife.config.ConfigurationObjectFactory.buildWithReplacements(ConfigurationObjectFactory.java:50)
	at org.apache.druid.guice.ConfigProvider.get(ConfigProvider.java:83)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at org.apache.druid.guice.LifecycleScope$1.get(LifecycleScope.java:68)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at org.apache.druid.guice.LifecycleScope$1.get(LifecycleScope.java:68)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)
	at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:141)
	at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:115)
	at org.apache.druid.cli.CliPeon.run(CliPeon.java:280)
	at org.apache.druid.cli.Main.main(Main.java:113)
	
We have already confirmed that connectivity with kafka nodes are proper. 
Can someone tell us what is the issue here and how to resolve it? Let me know if we need to provide any additional information.

**Comment by AdheipSingh** [comment]
does seems like a configuration mistake, can you double check your runtime properties, definitely not an operator error. Just make sure the runtime.properties has proper indentation etc, since they are mounted as configmaps.

**Comment by samitks** [comment]
Hey @AdheipSingh 

The indentation and all the `runtime.properties` looks fine to me. Attaching the complete config below:

> apiVersion: "druid.apache.org/v1alpha1"
kind: "Druid"
metadata:
  name: druid
  namespace: stage-druid1
spec:
  image: apache/druid:0.17.0
  startScript: /druid.sh
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
  services:
    - spec:
        type: ClusterIP
        clusterIP: None  
  commonConfigMountPath: "/opt/druid/conf/druid/cluster/_common"
  jvm.options: |-
    -server
    -XX:MaxDirectMemorySize=10240g
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -Dlog4j.debug
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
  log4j.config: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration status="WARN">
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
            </Console>
        </Appenders>
        <Loggers>
            <Root level="info">
                <AppenderRef ref="Console"/>
            </Root>
        </Loggers>
    </Configuration>
  common.runtime.properties: |
    # Zookeeper
    druid.zk.service.host=tiny-cluster-zk-0.tiny-cluster-zk.stage-druid1.svc.cluster.local
    druid.zk.paths.base=/druid
    druid.zk.service.compress=false
    # Metadata Store
    druid.metadata.storage.type=derby
    druid.metadata.storage.connector.connectURI=jdbc:derby://localhost:1527/var/druid/metadata.db;create=true
    druid.metadata.storage.connector.host=localhost
    druid.metadata.storage.connector.port=1527
    druid.metadata.storage.connector.createTables=true
    druid.javascript.enabled=true
    
    # Deep Storage
    druid.storage.type=local
    druid.storage.storageDirectory=/druid/data/deepstorage

    #
    # Extensions
    #
    druid.extensions.loadList=["druid-hdfs-storage", "druid-kafka-indexing-service", "druid-datasketches", "postgresql-metadata-storage","druid-s3-extensions"]
    #
    # Service discovery
    #
    druid.selectors.indexing.serviceName=druid/overlord
    druid.selectors.coordinator.serviceName=druid/coordinator
  nodes:
    brokers:
      nodeType: "broker"
      druid.port: 8088
      replicas: 1
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/query/broker"
      runtime.properties: |
        druid.service=druid/broker
        # HTTP server threads
        druid.broker.http.numConnections=5
        druid.server.http.numThreads=10
        # Processing threads and buffers
        druid.processing.buffer.sizeBytes=1
        druid.processing.numMergeBuffers=1
        druid.processing.numThreads=1
        druid.sql.enable=true
      extra.jvm.options: |-
        -Xmx1G
        -Xms1G
      volumeClaimTemplates:
        - metadata:
            name: "data-volume"
          spec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: "5Gi"
            storageClassName: "standard"
      volumeMounts:
        - mountPath: /druid/data
          name: data-volume
      resources:
        requests:
          memory: "1300Mi"
          cpu: "1"
        limits:
          memory: "1300Mi"
          cpu: "2"
      ingressAnnotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/"
      ingress:
        rules:
         - host: druid-broker.domain.com
           http:
             paths:
             - path: /
               backend:
                 serviceName: druid-druid-brokers
                 servicePort: 8088
    
    coordinators:
      nodeType: "coordinator"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/master/coordinator-overlord"
      runtime.properties: |
        druid.service=druid/coordinator

        # HTTP server threads
        druid.coordinator.startDelay=PT30S
        druid.coordinator.period=PT30S

        # Configure this coordinator to also run as Overlord
        druid.coordinator.asOverlord.enabled=true
        druid.coordinator.asOverlord.overlordService=druid/overlord
        druid.indexer.queue.startDelay=PT30S
        druid.indexer.runner.type=remote
        druid.indexer.storage.type=metadata
      extra.jvm.options: |-
        -Xmx1G
        -Xms1G
      volumeMounts:
        - mountPath: /druid/data
          name: data-volume
      volumeClaimTemplates:
      - metadata:
          name: "data-volume"
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: "5Gi"
          storageClassName: "standard"
      replicas: 1
      resources:
        requests:
          memory: "1300Mi"
          cpu: "1"
        limits:
          memory: "1300Mi"
          cpu: "1"
      ingressAnnotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/"
      ingress:
        rules:
         - host: druid-coordinator.domain.com
           http:
             paths:
             - path: /
               backend:
                 serviceName: druid-druid-coordinators
                 servicePort: 8088           
    historicals:
      nodeType: "historical"
      druid.port: 8088
      replicas: 1
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/data/historical"
      runtime.properties: |
        druid.service=druid/historical
        druid.server.http.numThreads=5
        druid.processing.buffer.sizeBytes=1
        druid.processing.numMergeBuffers=1
        druid.processing.numThreads=1
        # Segment storage
        druid.segmentCache.locations=[{\"path\":\"/druid/data/segments\",\"maxSize\":10737418240}]
        druid.server.maxSize=10737418240
      extra.jvm.options: |-
        -Xmx1G
        -Xms1G
      volumeMounts:
        - mountPath: /druid/data
          name: data-volume
      volumeClaimTemplates:
      - metadata:
          name: "data-volume"
        spec:
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: "5Gi"
          storageClassName: "standard"
      resources:
        requests:
          memory: "1200Mi"
          cpu: "1"
        limits:
          memory: "1200Mi"
          cpu: "1"
    
    routers:
      nodeType: "router"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/query/router"
      replicas: 1
      runtime.properties: |
        druid.service=druid/router

        # HTTP proxy
        druid.router.http.numConnections=10
        druid.router.http.readTimeout=PT5M
        druid.router.http.numMaxThreads=10
        druid.server.http.numThreads=10

        # Service discovery
        druid.router.defaultBrokerServiceName=druid/broker
        druid.router.coordinatorServiceName=druid/coordinator

        # Management proxy to coordinator / overlord: required for unified web console.
        druid.router.managementProxy.enabled=true   
      extra.jvm.options: |-
        -Xmx512M
        -Xms512M
      resources:
        requests:
          memory: "1G"
          cpu: "1"
        limits:
          memory: "1G"
          cpu: "1"
      ingressAnnotations:
        nginx.ingress.kubernetes.io/rewrite-target: "/"
      ingress:
        rules:
         - host: druid-router.domain.com
           http:
             paths:
             - path: /
               backend:
                 serviceName: druid-druid-routers
                 servicePort: 8088

    middlemanagers:
      podAnnotations:
        type: middlemanager
      druid.port: 8091
      extra.jvm.options: |-
          -Xmx3G
          -Xms3G
      nodeType: "middleManager"
      nodeConfigMountPath: /opt/druid/conf/druid/cluster/data/middleManager
      podDisruptionBudgetSpec:
        maxUnavailable: 1
      ports:
        - containerPort: 8100
          name: peon-0
      replicas: 1
      resources:
        limits:
          cpu: 1
          memory: 3500Mi
        requests:
          cpu: 1
          memory: 3500Mi
      livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /status/health
            port: 8091
      readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /status/health
            port: 8091
      runtime.properties: |-
          druid.service=druid/middleManager
          druid.worker.capacity=8
          druid.indexer.task.baseTaskDir=/druid/data/baseTaskDir
          druid.server.http.numThreads=10
          # Processing threads and buffers on Peons
          druid.indexer.fork.property.druid.processing.numMergeBuffers=2
          druid.indexer.fork.property.druid.processing.buffer.sizeBytes=100000000
          druid.indexer.fork.property.druid.processing.numThreads=1
      services:
        - spec:
            clusterIP: None
            ports:
              - name: tcp-service-port
                port: 8091
                targetPort: 8091
            type: ClusterIP
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 30Gi
            storageClassName: "standard"
      volumeMounts:
        - mountPath: /druid/data
          name: data-volume
      containerSecurityContext:
        capabilities:
          drop: ["ALL"]
      
 I also tried with different druid version (0.19.0) but still the same error. Also, I could not find anywhere using `1druid.host`.
 Can you check the above config and let me know if I have missed something?

**Comment by AdheipSingh** [comment]
can you try keeping all your middlemanager runtime.properties to ```runtime.properties: | ``` and not ```runtime.properties: |-```

**Comment by samitks** [comment]
Thanks, @AdheipSingh :)
That was the issue.
