### ISSUE TITLE
Cluster status unknown for example tiny cluster file

### ISSUE THREAD

**Issue by sohansamant8** [druid-io/druid-operator#242]
After deploying the tiny cluster example yaml file the status on the K8 UI is showing as unknown. Cluster status unknown on Kubernetes GCP for example tinycluster.yaml file.

**Comment by sohansamant8** [comment]
<img width="1526" alt="Screen Shot 2021-09-12 at 9 03 48 PM" src="https://user-images.githubusercontent.com/89788336/133009860-8e5d3681-4343-4727-8e68-dbc7ad1ff1ad.png">

**Comment by AdheipSingh** [comment]
pls give sufficient evidence to debug. Operator logs ? events ?  are pods running ?

**Comment by sohansamant** [comment]
My druid tiny cluster yaml file is getting deployed but the object status is showing unknown on the server. I have attached the screenshot about the same. Can you please help me in resolving this doubt? Any help on this is highly appreciated.

Also while I am building this, I am getting error in one of the previous steps which is deploying role.yaml file. The error says something like this "error while creating roles.rbac.authorization.k8s.io is forbidden for Sohan Samant" cannot create "roles" in API group "rbac.authorization.k8s.io" in namespace.

Is this could be the reason for my status being unknown? I am highly in need of your help!!

**Comment by sohansamant** [comment]
When I check the crd, it is showing me that it is registered..

NAME                                                             CREATED AT
capacityrequests.internal.autoscaling.k8s.io                     2020-12-10T17:53:46Z
druids.druid.apache.org                                          2021-09-13T02:17:46Z

Note: I am just following the steps given in the getting started documentation.

When I query to see pods: I don't see anything:

kubectl get pods -n druid-operator
NAME                             READY   STATUS    RESTARTS   AGE
druid-operator-757c948fd-q9mr9   1/1     Running   0          9h
tiny-cluster-zk-0                1/1     Running   0          18h

Please let me know if any more details are needed.

**Comment by AdheipSingh** [comment]
1. can you share the operator logs 
2. which ns are you deploying the CR in ?

**Comment by sohansamant** [comment]
2. I am deploying in namespace druid-operator. Do I need any specific namespace? Also when I create the CRD and try to delete it, the terminal gets frozen. It just hangs in there. Do you know any reason for this and how do I resolve this issue? 

also when I deploy the CRD with schema, it creates a yaml file which comes with hardcoded name of tiny-cluster and namespace as druid-operator. How can I change that for my custom process? I don't want to have it named as tiny-cluster

**Comment by sohansamant8** [comment]
@AdheipSingh  - I tried to resolve the above issue through some permissions were missing. However when I tried connecting metadata store to GCP Cloud SQL MySQL instance. The coordinator pod is failing. Below is the error log from pod -

021-09-15T12:46:55+0000 startup service coordinator
Setting druid.host=10.60.29.47 in /tmp/conf/druid/cluster/master/coordinator-overlord/runtime.properties
2021-09-15T12:46:57,340 INFO [main] org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.2.5.Final
2021-09-15T12:46:58,431 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-kafka-indexing-service], jars: snappy-java-1.1.7.3.jar, lz4-java-1.7.1.jar, druid-kafka-indexing-service-0.20.0.jar, kafka-clients-2.6.0.jar, zstd-jni-1.3.3-1.jar
2021-09-15T12:46:58,436 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-google-extensions], jars: druid-google-extensions-0.20.0.jar, google-api-services-storage-v1-rev20190523-1.26.0.jar
2021-09-15T12:46:58,563 INFO [main] org.apache.druid.cli.CliCoordinator - Coordinator is configured to act as Overlord as well (druid.coordinator.asOverlord.enabled = true).
2021-09-15T12:46:58,805 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-kafka-indexing-service], jars: snappy-java-1.1.7.3.jar, lz4-java-1.7.1.jar, druid-kafka-indexing-service-0.20.0.jar, kafka-clients-2.6.0.jar, zstd-jni-1.3.3-1.jar
2021-09-15T12:46:58,808 INFO [main] org.apache.druid.initialization.Initialization - Loading extension [druid-google-extensions], jars: druid-google-extensions-0.20.0.jar, google-api-services-storage-v1-rev20190523-1.26.0.jar
2021-09-15T12:46:58,824 INFO [main] org.apache.druid.storage.google.GoogleStorageDruidModule - Getting jackson modules...
2021-09-15T12:46:59,655 INFO [main] org.apache.druid.storage.google.GoogleStorageDruidModule - Configuring GoogleStorageDruidModule...
2021-09-15T12:47:00,656 INFO [main] org.apache.curator.utils.Compatibility - Running in ZooKeeper 3.4.x compatibility mode
2021-09-15T12:47:00,658 INFO [main] org.apache.curator.utils.Compatibility - Using emulated InjectSessionExpiration
Exception in thread "main" java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Unknown provider[mysql] of Key[type=org.apache.druid.metadata.MetadataStorageConnector, annotation=[none]], known options[[derby]]
  at org.apache.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:109) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.derby.DerbyMetadataStorageDruidModule)
  while locating org.apache.druid.metadata.MetadataStorageConnector
    for the 1st parameter of org.apache.druid.guice.JacksonConfigManagerModule.getConfigManager(JacksonConfigManagerModule.java:52)
  at org.apache.druid.guice.JacksonConfigManagerModule.getConfigManager(JacksonConfigManagerModule.java:52) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.JacksonConfigManagerModule)
  while locating org.apache.druid.common.config.ConfigManager
    for the 1st parameter of org.apache.druid.common.config.JacksonConfigManager.<init>(JacksonConfigManager.java:49)
  at org.apache.druid.guice.JacksonConfigManagerModule.configure(JacksonConfigManagerModule.java:41) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.JacksonConfigManagerModule)
  while locating org.apache.druid.common.config.JacksonConfigManager
    for the 1st parameter of org.apache.druid.guice.JacksonConfigProvider.configure(JacksonConfigProvider.java:65)
  at org.apache.druid.guice.JacksonConfigProvider.bind(JacksonConfigProvider.java:38) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)

2) Unknown provider[mysql] of Key[type=org.apache.druid.server.audit.AuditManagerProvider, annotation=[none]], known options[[derby]]
  at org.apache.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:109) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.derby.DerbyMetadataStorageDruidModule)
  while locating org.apache.druid.server.audit.AuditManagerProvider
  at org.apache.druid.cli.CliCoordinator$1.configure(CliCoordinator.java:182) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliCoordinator$1)
  while locating org.apache.druid.audit.AuditManager
    for the 3rd parameter of org.apache.druid.common.config.JacksonConfigManager.<init>(JacksonConfigManager.java:49)
  at org.apache.druid.guice.JacksonConfigManagerModule.configure(JacksonConfigManagerModule.java:41) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.JacksonConfigManagerModule)
  while locating org.apache.druid.common.config.JacksonConfigManager
    for the 1st parameter of org.apache.druid.guice.JacksonConfigProvider.configure(JacksonConfigProvider.java:65)
  at org.apache.druid.guice.JacksonConfigProvider.bind(JacksonConfigProvider.java:38) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)

2 errors
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:72)
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:62)
	at org.apache.druid.cli.Main.main(Main.java:113)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Unknown provider[mysql] of Key[type=org.apache.druid.metadata.MetadataStorageConnector, annotation=[none]], known options[[derby]]
  at org.apache.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:109) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.derby.DerbyMetadataStorageDruidModule)
  while locating org.apache.druid.metadata.MetadataStorageConnector
    for the 1st parameter of org.apache.druid.guice.JacksonConfigManagerModule.getConfigManager(JacksonConfigManagerModule.java:52)
  at org.apache.druid.guice.JacksonConfigManagerModule.getConfigManager(JacksonConfigManagerModule.java:52) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.JacksonConfigManagerModule)
  while locating org.apache.druid.common.config.ConfigManager
    for the 1st parameter of org.apache.druid.common.config.JacksonConfigManager.<init>(JacksonConfigManager.java:49)
  at org.apache.druid.guice.JacksonConfigManagerModule.configure(JacksonConfigManagerModule.java:41) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.JacksonConfigManagerModule)
  while locating org.apache.druid.common.config.JacksonConfigManager
    for the 1st parameter of org.apache.druid.guice.JacksonConfigProvider.configure(JacksonConfigProvider.java:65)
  at org.apache.druid.guice.JacksonConfigProvider.bind(JacksonConfigProvider.java:38) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)

2) Unknown provider[mysql] of Key[type=org.apache.druid.server.audit.AuditManagerProvider, annotation=[none]], known options[[derby]]
  at org.apache.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:109) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.metadata.storage.derby.DerbyMetadataStorageDruidModule)
  while locating org.apache.druid.server.audit.AuditManagerProvider
  at org.apache.druid.cli.CliCoordinator$1.configure(CliCoordinator.java:182) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliCoordinator$1)
  while locating org.apache.druid.audit.AuditManager
    for the 3rd parameter of org.apache.druid.common.config.JacksonConfigManager.<init>(JacksonConfigManager.java:49)
  at org.apache.druid.guice.JacksonConfigManagerModule.configure(JacksonConfigManagerModule.java:41) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.guice.JacksonConfigManagerModule)
  while locating org.apache.druid.common.config.JacksonConfigManager
    for the 1st parameter of org.apache.druid.guice.JacksonConfigProvider.configure(JacksonConfigProvider.java:65)
  at org.apache.druid.guice.JacksonConfigProvider.bind(JacksonConfigProvider.java:38) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliOverlord$1)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.apache.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:431)
	at org.apache.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:69)
	... 2 more

--- Configuration Yaml file --

# Metadata Store
    druid.metadata.storage.type=mysql
    #druid.metadata.storage.connector.connectURI=jdbc:derby://localhost:1527/druid/data/derbydb/metadata.db;create=true
    druid.metadata.storage.connector.host=x.x.x.x
    druid.metadata.storage.connector.port=3306
    druid.metadata.storage.connector.createTables=true
    druid.metadata.storage.connector.user=xxxx
    druid.metadata.storage.connector.password=xxxx

**Comment by AdheipSingh** [comment]
Metadata storage
```
druid.metadata.storage.type=mysql
druid.metadata.storage.connector.connectURI=jdbc:mysql://${MYSQL_HOST}/${DB_NAME}
druid.metadata.storage.connector.user=${DB_USER}
druid.metadata.storage.connector.password={ "type": "environment", "variable": "DB_PASSWORD" }
```
This should work

**Comment by sohansamant8** [comment]
Thanks for your response. I tried that but is isn't working. MySQL needs additional connector jar to be present on K8 cluster. So while I am trying to attach persistent volume to K8 cluster and then connect it with tiny-cluster it isn't working. I am adding following configs in tiny-cluster.yaml file 

volumeMounts:
  - mountPath: /test-pd
    name: test-volume
volumes:
  - name: test-volume
  # This GCE PD must already exist.
    gcePersistentDisk:
      pdName: com-metacx-dev-pd
      fsType: ext4

Error:

kubectl logs druid-druid-cluster-coordinators -n druid-testing
Error from server (BadRequest): container "druid-druid-cluster-coordinators" in pod "druid-druid-cluster-coordinators" is waiting to start: ContainerCreating.

Can you please help with specifying what's the correct location where I need to place these volume tags?

Thanks!

**Comment by AdheipSingh** [comment]
@sohansamant you need the mysql extension present in your common runtime properties . 
```
druid.extensions.loadList=["mysql-metadata-storage"]
```

**Comment by sohansamant8** [comment]
@AdheipSingh  - To resolve the above error, I am trying to copy the the jar into persistent volume. but I cannot add persistent volume in tiny-cluster.yaml file. Can you please help in adding those tags into the yaml file?

Thanks!

**Comment by AdheipSingh** [comment]
can you add this config in your common properties
```
druid.extensions.directory=./extensions
```
> I am trying to copy the the jar into persistent volume.

This isn't a preferred way of running druid. Regardless tiny cluster is just an example and uses empty dir and hostpath for volumes. Here are some examples for running with storage class pvc's on cloud.

- https://github.com/druid-io/druid-operator/pull/241/files
- https://gist.github.com/AdheipSingh/2d3ed8fcd3b57a5b3e1a01f0bda3ba27

**Comment by sohansamant8** [comment]
Thanks for sharing the files..I will try to create my druid yaml in the similar manner. However, do you have examples for the corresponding zookeeper yaml and any connection that you did for GoogleSQL and GoogleStorage?
